# Header
menu:
  Home: /
  About: /about
  Instagram: https://www.instagram.com/amy_e_carrigan/
  Redbubble: https://www.redbubble.com/people/amybeth
  Society6: https://society6.com/amybethcarrigan

# Logo Image Source
logo_src: /images/logo.svg

# Theme Main Subtitle
subtitle_main: Bloomin' good pattern design.

# Theme Secondary subtitle
susbtitle_secondary: We are under construction, so please be patient if you can't find what you're looking for. I build websites for my day job, so building this one sometimes has to wait for times when I hate the internet less. Feel free to contact me at hello (at) tuimaladesign (dot) com with any questions!

# Footer About Section
about_footer: 

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: 
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: 
facebook_url: 
instagram_url: https://www.instagram.com/amy_e_carrigan/
dribble_url: 
github_url: 
googleplus_url: 
behance_url: 
fivehundredpx_url: 
email_url: mailto:hello@tuimaladesign.com
rss_url: 
